language: python
python:
- '2.6'
- '2.7'
install:
- pip install .
- pip install pylint
- pip install -r requirements.txt
script:
- pylint -E tubestatus
deploy:
  provider: pypi
  user: jacob.tomlinson
  password:
    secure: "ZNB3BQ7KRFGbu6FO3bMDwNmNW58vWyDPv8Cq4B6AhlLSJhJBXlQ7ZP5MhHFq/FM0QYQyBMi5l/HxfVKpGSpzE2GuDrHv0OK6ZG7RQGV51VYNNadVXiYq72bouEW8SPxi9j8tn9A1PxugeA9M4X98ukPfRoMCXUxfvaapAFvXAcQ="
  on:
    tags: true
    all_branches: true
    repo: jacobtomlinson/tube-status
